### ISSUE TITLE
webpack error

### ISSUE THREAD

**Issue by tophe** [slashdotdash/phoenix-react-redux-example#4]
hello, 
doing 
git clone ..
then 
npm install ...
[Tophe:/data/work/elixir/redux/phoenix-react-redux-example] master 130 ± git status
# On branch master

nothing to commit (working directory clean)
[Tophe:/data/work/elixir/redux/phoenix-react-redux-example] master ± node -v
v4.2.3

[Tophe:/data/work/elixir/redux/phoenix-react-redux-example] master ± webpack --watch --color
Hash: fe16ed6a9b9035eb5caa
Version: webpack 1.12.9
Time: 6257ms
 Asset    Size  Chunks             Chunk Names
app.js  911 kB       0  [emitted]  main
    + 334 hidden modules

ERROR in ./deps/phoenix/web/static/js/phoenix.js
Module build failed: TypeError: /data/work/elixir/redux/phoenix-react-redux-example/deps/phoenix/web/static/js/phoenix.js: Duplicate declaration "channel"
  454 | 
  455 |   channel(topic, chanParams = {}){

> 456 |     let channel = new Channel(topic, chanParams, this)
>       |         ^
>   457 |     this.channels.push(channel)
>   458 |     return channel
>   459 |   }
>     at File.buildCodeFrameError (/data/work/elixir/redux/phoenix-react-redux-example/node_modules/babel-core/lib/transformation/file/index.js:407:15)
>     at Scope.checkBlockScopedCollisions (/data/work/elixir/redux/phoenix-react-redux-example/node_modules/babel-core/node_modules/babel-traverse/lib/scope/index.js:490:27)
>     at Scope.<anonymous> (/data/work/elixir/redux/phoenix-react-redux-example/node_modules/babel-core/node_modules/babel-traverse/lib/scope/index.js:675:18)
>     at Scope.registerBinding (/data/work/elixir/redux/phoenix-react-redux-example/node_modules/babel-core/node_modules/babel-traverse/lib/scope/index.js:689:8)
>     at Scope.registerDeclaration (/data/work/elixir/redux/phoenix-react-redux-example/node_modules/babel-core/node_modules/babel-traverse/lib/scope/index.js:577:14)
>     at Object.BlockScoped (/data/work/elixir/redux/phoenix-react-redux-example/node_modules/babel-core/node_modules/babel-traverse/lib/scope/index.js:224:28)
>     at Object.newFn (/data/work/elixir/redux/phoenix-react-redux-example/node_modules/babel-core/node_modules/babel-traverse/lib/visitors.js:309:17)
>     at NodePath._call (/data/work/elixir/redux/phoenix-react-redux-example/node_modules/babel-core/node_modules/babel-traverse/lib/path/context.js:74:18)
>     at NodePath.call (/data/work/elixir/redux/phoenix-react-redux-example/node_modules/babel-core/node_modules/babel-traverse/lib/path/context.js:42:14)
>     at NodePath.visit (/data/work/elixir/redux/phoenix-react-redux-example/node_modules/babel-core/node_modules/babel-traverse/lib/path/context.js:104:12)
>     at TraversalContext.visitQueue (/data/work/elixir/redux/phoenix-react-redux-example/node_modules/babel-core/node_modules/babel-traverse/lib/context.js:153:16)
>     at TraversalContext.visitMultiple (/data/work/elixir/redux/phoenix-react-redux-example/node_modules/babel-core/node_modules/babel-traverse/lib/context.js:108:17)
>     at TraversalContext.visit (/data/work/elixir/redux/phoenix-react-redux-example/node_modules/babel-core/node_modules/babel-traverse/lib/context.js:195:19)
>     at Function.traverse.node (/data/work/elixir/redux/phoenix-react-redux-example/node_modules/babel-core/node_modules/babel-traverse/lib/index.js:139:17)
>     at NodePath.visit (/data/work/elixir/redux/phoenix-react-redux-example/node_modules/babel-core/node_modules/babel-traverse/lib/path/context.js:114:22)
>     at TraversalContext.visitQueue (/data/work/elixir/redux/phoenix-react-redux-example/node_modules/babel-core/node_modules/babel-traverse/lib/context.js:153:16)
>     at TraversalContext.visitSingle (/data/work/elixir/redux/phoenix-react-redux-example/node_modules/babel-core/node_modules/babel-traverse/lib/context.js:113:19)
>     at TraversalContext.visit (/data/work/elixir/redux/phoenix-react-redux-example/node_modules/babel-core/node_modules/babel-traverse/lib/context.js:197:19)
>     at Function.traverse.node (/data/work/elixir/redux/phoenix-react-redux-example/node_modules/babel-core/node_modules/babel-traverse/lib/index.js:139:17)
>     at Object.traverse [as default](/data/work/elixir/redux/phoenix-react-redux-example/node_modules/babel-core/node_modules/babel-traverse/lib/index.js:61:12)
>     at NodePath.traverse (/data/work/elixir/redux/phoenix-react-redux-example/node_modules/babel-core/node_modules/babel-traverse/lib/path/index.js:152:23)
>     at Scope.crawl (/data/work/elixir/redux/phoenix-react-redux-example/node_modules/babel-core/node_modules/babel-traverse/lib/scope/index.js:927:10)
>     at Scope.init (/data/work/elixir/redux/phoenix-react-redux-example/node_modules/babel-core/node_modules/babel-traverse/lib/scope/index.js:839:32)
>     at NodePath.setScope (/data/work/elixir/redux/phoenix-react-redux-example/node_modules/babel-core/node_modules/babel-traverse/lib/path/context.js:150:30)
>     at NodePath.setContext (/data/work/elixir/redux/phoenix-react-redux-example/node_modules/babel-core/node_modules/babel-traverse/lib/path/context.js:165:8)
>     at NodePath.pushContext (/data/work/elixir/redux/phoenix-react-redux-example/node_modules/babel-core/node_modules/babel-traverse/lib/path/context.js:240:8)
>     at TraversalContext.visitQueue (/data/work/elixir/redux/phoenix-react-redux-example/node_modules/babel-core/node_modules/babel-traverse/lib/context.js:143:12)
>     at TraversalContext.visitSingle (/data/work/elixir/redux/phoenix-react-redux-example/node_modules/babel-core/node_modules/babel-traverse/lib/context.js:113:19)
>     at TraversalContext.visit (/data/work/elixir/redux/phoenix-react-redux-example/node_modules/babel-core/node_modules/babel-traverse/lib/context.js:197:19)
>     at Function.traverse.node (/data/work/elixir/redux/phoenix-react-redux-example/node_modules/babel-core/node_modules/babel-traverse/lib/index.js:139:17)
>  @ ./web/static/js/channel.js 8:15-33

ERROR in ENOENT, stat '/data/work/elixir/redux/phoenix-react-redux-example/web/static/assets'

any idea ?
after than, when I hit phoenix, I just have the title, no add button.

**Comment by jhlllnd** [comment]
I think you are requiring phoenix twice.

ERROR in ENOENT just means that you are missing the folder web/static/assets

Edit:

I think you missed the part with `mix deps.get`

Try this steps

```
npm install
mkdir web/static/assets
mix deps.get
mix phoenix.server
```
